# Generated by Django 4.2.7 on 2023-11-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtransaction',
            old_name='event',
            new_name='event_id',
        ),
    ]
