# Generated by Django 4.2.7 on 2023-11-28 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_event_bookingtransaction_event_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtransaction',
            old_name='uuid',
            new_name='id',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('invoice', models.FileField(upload_to='invoices/')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtransaction')),
            ],
        ),
    ]
