# Generated by Django 4.2.7 on 2023-11-28 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_uuid_bookingtransaction_id_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='transaction',
        ),
        migrations.AddField(
            model_name='bookingtransaction',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.invoice'),
        ),
        migrations.AlterField(
            model_name='bookingtransaction',
            name='event_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingtransaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=models.FileField(upload_to=''),
        ),
    ]
