# Generated by Django 4.2.7 on 2023-11-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_invoice_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
