# Generated by Django 4.2.7 on 2023-11-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_invoice_payment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
